{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "\n",
    "import numpy as np\n",
    "import altair as alt\n",
    "import pandas as pd\n",
    "\n",
    "import snowflake.connector\n",
    "from snowflake.connector.pandas_tools import write_pandas\n",
    "\n",
    "import streamlit as st"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "host = st.secrets['snowflake']['host']\n",
    "user = st.secrets['snowflake']['user']\n",
    "password = st.secrets['snowflake']['password']\n",
    "account = st.secrets['snowflake']['account']\n",
    "warehouse = st.secrets['snowflake']['warehouse']\n",
    "database = st.secrets['snowflake']['database']\n",
    "schema = st.secrets['snowflake']['schema']\n",
    "\n",
    "cd = {\n",
    "    'host' : host,\n",
    "    'user' : user,\n",
    "    'password' : password,\n",
    "    'account' : account,\n",
    "    'warehouse' : warehouse,\n",
    "    'database' : database,\n",
    "    'schema' : schema\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [],
   "source": [
    "def snowflake_query(snowflake_schema, snowflake_table, cd):\n",
    "\n",
    "    query = f\"select * from {snowflake_schema}.{snowflake_table}\"\n",
    "\n",
    "    connector = snowflake.connector.connect(\n",
    "        host=cd['host'],\n",
    "        user=cd['user'],\n",
    "        password=cd['password'],\n",
    "        account=cd['account'],\n",
    "        warehouse=cd['warehouse'],\n",
    "        database=cd['database'],\n",
    "        schema=cd['schema'])\n",
    "\n",
    "    try:\n",
    "        cursor = connector.cursor().execute(query)\n",
    "    finally:\n",
    "        connector.close()\n",
    "    df = cursor.fetch_pandas_all()\n",
    "\n",
    "    return df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2022-12-10 14:24:10.547 Snowflake Connector for Python Version: 2.7.12, Python Version: 3.9.13, Platform: macOS-10.16-x86_64-i386-64bit\n",
      "2022-12-10 14:24:10.550 This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.\n",
      "2022-12-10 14:24:12.042 query: [select * from RAW.CSV__PLACES_DATA]\n",
      "2022-12-10 14:24:12.620 query execution done\n",
      "2022-12-10 14:24:12.622 closed\n",
      "2022-12-10 14:24:12.881 No async queries seem to be running, deleting session\n",
      "2022-12-10 14:24:13.141 Failed to add log to telemetry.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 96, in try_add_log_to_batch\n",
      "    self.add_log_to_batch(telemetry_data)\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 83, in add_log_to_batch\n",
      "    raise Exception(\"Attempted to add log when TelemetryClient is closed\")\n",
      "Exception: Attempted to add log when TelemetryClient is closed\n",
      "2022-12-10 14:24:13.156 Failed to add log to telemetry.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 96, in try_add_log_to_batch\n",
      "    self.add_log_to_batch(telemetry_data)\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 83, in add_log_to_batch\n",
      "    raise Exception(\"Attempted to add log when TelemetryClient is closed\")\n",
      "Exception: Attempted to add log when TelemetryClient is closed\n",
      "2022-12-10 14:24:13.159 Snowflake Connector for Python Version: 2.7.12, Python Version: 3.9.13, Platform: macOS-10.16-x86_64-i386-64bit\n",
      "2022-12-10 14:24:13.160 This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.\n",
      "2022-12-10 14:24:14.480 query: [select * from RAW.CSV__TRANSIT_DATA]\n",
      "2022-12-10 14:24:15.075 query execution done\n",
      "2022-12-10 14:24:15.076 closed\n",
      "2022-12-10 14:24:15.294 No async queries seem to be running, deleting session\n",
      "2022-12-10 14:24:15.567 Failed to add log to telemetry.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 96, in try_add_log_to_batch\n",
      "    self.add_log_to_batch(telemetry_data)\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 83, in add_log_to_batch\n",
      "    raise Exception(\"Attempted to add log when TelemetryClient is closed\")\n",
      "Exception: Attempted to add log when TelemetryClient is closed\n",
      "2022-12-10 14:24:15.570 Failed to add log to telemetry.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 96, in try_add_log_to_batch\n",
      "    self.add_log_to_batch(telemetry_data)\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 83, in add_log_to_batch\n",
      "    raise Exception(\"Attempted to add log when TelemetryClient is closed\")\n",
      "Exception: Attempted to add log when TelemetryClient is closed\n",
      "2022-12-10 14:24:15.573 Snowflake Connector for Python Version: 2.7.12, Python Version: 3.9.13, Platform: macOS-10.16-x86_64-i386-64bit\n",
      "2022-12-10 14:24:15.574 This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.\n",
      "2022-12-10 14:24:16.803 query: [select * from RAW.JSON__INDEX_META]\n",
      "2022-12-10 14:24:17.128 query execution done\n",
      "2022-12-10 14:24:17.129 closed\n",
      "2022-12-10 14:24:17.335 No async queries seem to be running, deleting session\n",
      "2022-12-10 14:24:17.583 Failed to add log to telemetry.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 96, in try_add_log_to_batch\n",
      "    self.add_log_to_batch(telemetry_data)\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 83, in add_log_to_batch\n",
      "    raise Exception(\"Attempted to add log when TelemetryClient is closed\")\n",
      "Exception: Attempted to add log when TelemetryClient is closed\n",
      "2022-12-10 14:24:19.153 Failed to add log to telemetry.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 96, in try_add_log_to_batch\n",
      "    self.add_log_to_batch(telemetry_data)\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 83, in add_log_to_batch\n",
      "    raise Exception(\"Attempted to add log when TelemetryClient is closed\")\n",
      "Exception: Attempted to add log when TelemetryClient is closed\n",
      "2022-12-10 14:24:19.154 Failed to add log to telemetry.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 96, in try_add_log_to_batch\n",
      "    self.add_log_to_batch(telemetry_data)\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 83, in add_log_to_batch\n",
      "    raise Exception(\"Attempted to add log when TelemetryClient is closed\")\n",
      "Exception: Attempted to add log when TelemetryClient is closed\n",
      "2022-12-10 14:24:19.159 Snowflake Connector for Python Version: 2.7.12, Python Version: 3.9.13, Platform: macOS-10.16-x86_64-i386-64bit\n",
      "2022-12-10 14:24:19.161 This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.\n",
      "2022-12-10 14:24:20.233 query: [select * from RAW.JSON__DETAILS]\n",
      "2022-12-10 14:24:20.592 query execution done\n",
      "2022-12-10 14:24:20.593 closed\n",
      "2022-12-10 14:24:20.810 No async queries seem to be running, deleting session\n",
      "2022-12-10 14:24:21.196 Failed to add log to telemetry.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 96, in try_add_log_to_batch\n",
      "    self.add_log_to_batch(telemetry_data)\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 83, in add_log_to_batch\n",
      "    raise Exception(\"Attempted to add log when TelemetryClient is closed\")\n",
      "Exception: Attempted to add log when TelemetryClient is closed\n",
      "2022-12-10 14:24:22.887 Failed to add log to telemetry.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 96, in try_add_log_to_batch\n",
      "    self.add_log_to_batch(telemetry_data)\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 83, in add_log_to_batch\n",
      "    raise Exception(\"Attempted to add log when TelemetryClient is closed\")\n",
      "Exception: Attempted to add log when TelemetryClient is closed\n",
      "2022-12-10 14:24:22.888 Failed to add log to telemetry.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 96, in try_add_log_to_batch\n",
      "    self.add_log_to_batch(telemetry_data)\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 83, in add_log_to_batch\n",
      "    raise Exception(\"Attempted to add log when TelemetryClient is closed\")\n",
      "Exception: Attempted to add log when TelemetryClient is closed\n"
     ]
    }
   ],
   "source": [
    "raw_places = snowflake_query('RAW', 'CSV__PLACES_DATA', cd)\n",
    "raw_transit = snowflake_query('RAW', 'CSV__TRANSIT_DATA', cd)\n",
    "raw_index_meta = snowflake_query('RAW', 'JSON__INDEX_META', cd)\n",
    "raw_property_details = snowflake_query('RAW', 'JSON__DETAILS', cd)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2022-12-10 14:28:39.783 Snowflake Connector for Python Version: 2.7.12, Python Version: 3.9.13, Platform: macOS-10.16-x86_64-i386-64bit\n",
      "2022-12-10 14:28:39.788 This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.\n",
      "2022-12-10 14:28:41.160 query: [select * from STAGING.STG__DETAILS]\n",
      "2022-12-10 14:28:42.472 query execution done\n",
      "2022-12-10 14:28:42.473 closed\n",
      "2022-12-10 14:28:42.688 No async queries seem to be running, deleting session\n",
      "2022-12-10 14:28:42.945 Failed to add log to telemetry.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 96, in try_add_log_to_batch\n",
      "    self.add_log_to_batch(telemetry_data)\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 83, in add_log_to_batch\n",
      "    raise Exception(\"Attempted to add log when TelemetryClient is closed\")\n",
      "Exception: Attempted to add log when TelemetryClient is closed\n",
      "2022-12-10 14:28:44.551 Failed to add log to telemetry.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 96, in try_add_log_to_batch\n",
      "    self.add_log_to_batch(telemetry_data)\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 83, in add_log_to_batch\n",
      "    raise Exception(\"Attempted to add log when TelemetryClient is closed\")\n",
      "Exception: Attempted to add log when TelemetryClient is closed\n",
      "2022-12-10 14:28:44.553 Failed to add log to telemetry.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 96, in try_add_log_to_batch\n",
      "    self.add_log_to_batch(telemetry_data)\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 83, in add_log_to_batch\n",
      "    raise Exception(\"Attempted to add log when TelemetryClient is closed\")\n",
      "Exception: Attempted to add log when TelemetryClient is closed\n",
      "2022-12-10 14:28:44.555 Snowflake Connector for Python Version: 2.7.12, Python Version: 3.9.13, Platform: macOS-10.16-x86_64-i386-64bit\n",
      "2022-12-10 14:28:44.557 This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.\n",
      "2022-12-10 14:28:45.840 query: [select * from STAGING.STG__DEVELOPERS]\n",
      "2022-12-10 14:28:46.866 query execution done\n",
      "2022-12-10 14:28:46.867 closed\n",
      "2022-12-10 14:28:47.085 No async queries seem to be running, deleting session\n",
      "2022-12-10 14:28:47.342 Failed to add log to telemetry.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 96, in try_add_log_to_batch\n",
      "    self.add_log_to_batch(telemetry_data)\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 83, in add_log_to_batch\n",
      "    raise Exception(\"Attempted to add log when TelemetryClient is closed\")\n",
      "Exception: Attempted to add log when TelemetryClient is closed\n",
      "2022-12-10 14:28:47.345 Failed to add log to telemetry.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 96, in try_add_log_to_batch\n",
      "    self.add_log_to_batch(telemetry_data)\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 83, in add_log_to_batch\n",
      "    raise Exception(\"Attempted to add log when TelemetryClient is closed\")\n",
      "Exception: Attempted to add log when TelemetryClient is closed\n",
      "2022-12-10 14:28:47.345 Snowflake Connector for Python Version: 2.7.12, Python Version: 3.9.13, Platform: macOS-10.16-x86_64-i386-64bit\n",
      "2022-12-10 14:28:47.346 This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.\n",
      "2022-12-10 14:28:48.664 query: [select * from STAGING.STG__FEATURES]\n",
      "2022-12-10 14:28:49.682 query execution done\n",
      "2022-12-10 14:28:49.683 closed\n",
      "2022-12-10 14:28:49.882 No async queries seem to be running, deleting session\n",
      "2022-12-10 14:28:50.129 Failed to add log to telemetry.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 96, in try_add_log_to_batch\n",
      "    self.add_log_to_batch(telemetry_data)\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 83, in add_log_to_batch\n",
      "    raise Exception(\"Attempted to add log when TelemetryClient is closed\")\n",
      "Exception: Attempted to add log when TelemetryClient is closed\n",
      "2022-12-10 14:28:51.241 Failed to add log to telemetry.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 96, in try_add_log_to_batch\n",
      "    self.add_log_to_batch(telemetry_data)\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 83, in add_log_to_batch\n",
      "    raise Exception(\"Attempted to add log when TelemetryClient is closed\")\n",
      "Exception: Attempted to add log when TelemetryClient is closed\n",
      "2022-12-10 14:28:51.242 Failed to add log to telemetry.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 96, in try_add_log_to_batch\n",
      "    self.add_log_to_batch(telemetry_data)\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 83, in add_log_to_batch\n",
      "    raise Exception(\"Attempted to add log when TelemetryClient is closed\")\n",
      "Exception: Attempted to add log when TelemetryClient is closed\n",
      "2022-12-10 14:28:51.244 Snowflake Connector for Python Version: 2.7.12, Python Version: 3.9.13, Platform: macOS-10.16-x86_64-i386-64bit\n",
      "2022-12-10 14:28:51.246 This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.\n",
      "2022-12-10 14:28:52.770 query: [select * from STAGING.STG__PLACES]\n",
      "2022-12-10 14:28:53.517 query execution done\n",
      "2022-12-10 14:28:53.519 closed\n",
      "2022-12-10 14:28:53.723 No async queries seem to be running, deleting session\n",
      "2022-12-10 14:28:53.982 Failed to add log to telemetry.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 96, in try_add_log_to_batch\n",
      "    self.add_log_to_batch(telemetry_data)\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 83, in add_log_to_batch\n",
      "    raise Exception(\"Attempted to add log when TelemetryClient is closed\")\n",
      "Exception: Attempted to add log when TelemetryClient is closed\n",
      "2022-12-10 14:28:53.987 Failed to add log to telemetry.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 96, in try_add_log_to_batch\n",
      "    self.add_log_to_batch(telemetry_data)\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 83, in add_log_to_batch\n",
      "    raise Exception(\"Attempted to add log when TelemetryClient is closed\")\n",
      "Exception: Attempted to add log when TelemetryClient is closed\n",
      "2022-12-10 14:28:53.990 Snowflake Connector for Python Version: 2.7.12, Python Version: 3.9.13, Platform: macOS-10.16-x86_64-i386-64bit\n",
      "2022-12-10 14:28:53.991 This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.\n",
      "2022-12-10 14:28:55.401 query: [select * from STAGING.STG__PROJECTS_LIST]\n",
      "2022-12-10 14:28:56.828 query execution done\n",
      "2022-12-10 14:28:56.830 closed\n",
      "2022-12-10 14:28:57.045 No async queries seem to be running, deleting session\n",
      "2022-12-10 14:28:57.305 Failed to add log to telemetry.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 96, in try_add_log_to_batch\n",
      "    self.add_log_to_batch(telemetry_data)\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 83, in add_log_to_batch\n",
      "    raise Exception(\"Attempted to add log when TelemetryClient is closed\")\n",
      "Exception: Attempted to add log when TelemetryClient is closed\n",
      "2022-12-10 14:28:58.353 Failed to add log to telemetry.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 96, in try_add_log_to_batch\n",
      "    self.add_log_to_batch(telemetry_data)\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 83, in add_log_to_batch\n",
      "    raise Exception(\"Attempted to add log when TelemetryClient is closed\")\n",
      "Exception: Attempted to add log when TelemetryClient is closed\n",
      "2022-12-10 14:28:58.354 Failed to add log to telemetry.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 96, in try_add_log_to_batch\n",
      "    self.add_log_to_batch(telemetry_data)\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 83, in add_log_to_batch\n",
      "    raise Exception(\"Attempted to add log when TelemetryClient is closed\")\n",
      "Exception: Attempted to add log when TelemetryClient is closed\n",
      "2022-12-10 14:28:58.356 Snowflake Connector for Python Version: 2.7.12, Python Version: 3.9.13, Platform: macOS-10.16-x86_64-i386-64bit\n",
      "2022-12-10 14:28:58.357 This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.\n",
      "2022-12-10 14:28:59.433 query: [select * from STAGING.STG__TRANSIT]\n",
      "2022-12-10 14:29:00.186 query execution done\n",
      "2022-12-10 14:29:00.188 closed\n",
      "2022-12-10 14:29:00.412 No async queries seem to be running, deleting session\n",
      "2022-12-10 14:29:00.684 Failed to add log to telemetry.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 96, in try_add_log_to_batch\n",
      "    self.add_log_to_batch(telemetry_data)\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 83, in add_log_to_batch\n",
      "    raise Exception(\"Attempted to add log when TelemetryClient is closed\")\n",
      "Exception: Attempted to add log when TelemetryClient is closed\n",
      "2022-12-10 14:29:00.690 Failed to add log to telemetry.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 96, in try_add_log_to_batch\n",
      "    self.add_log_to_batch(telemetry_data)\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 83, in add_log_to_batch\n",
      "    raise Exception(\"Attempted to add log when TelemetryClient is closed\")\n",
      "Exception: Attempted to add log when TelemetryClient is closed\n",
      "2022-12-10 14:29:00.692 Snowflake Connector for Python Version: 2.7.12, Python Version: 3.9.13, Platform: macOS-10.16-x86_64-i386-64bit\n",
      "2022-12-10 14:29:00.693 This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.\n",
      "2022-12-10 14:29:02.038 query: [select * from STAGING.STG__VACANCY]\n",
      "2022-12-10 14:29:03.007 query execution done\n",
      "2022-12-10 14:29:03.009 closed\n",
      "2022-12-10 14:29:03.251 No async queries seem to be running, deleting session\n",
      "2022-12-10 14:29:03.513 Failed to add log to telemetry.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 96, in try_add_log_to_batch\n",
      "    self.add_log_to_batch(telemetry_data)\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 83, in add_log_to_batch\n",
      "    raise Exception(\"Attempted to add log when TelemetryClient is closed\")\n",
      "Exception: Attempted to add log when TelemetryClient is closed\n",
      "2022-12-10 14:29:03.521 Failed to add log to telemetry.\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 96, in try_add_log_to_batch\n",
      "    self.add_log_to_batch(telemetry_data)\n",
      "  File \"/Users/tanhtra/opt/anaconda3/envs/bootcamp/lib/python3.9/site-packages/snowflake/connector/telemetry.py\", line 83, in add_log_to_batch\n",
      "    raise Exception(\"Attempted to add log when TelemetryClient is closed\")\n",
      "Exception: Attempted to add log when TelemetryClient is closed\n"
     ]
    }
   ],
   "source": [
    "stg_details = snowflake_query('STAGING', 'STG__DETAILS', cd)\n",
    "stg_developers = snowflake_query('STAGING', 'STG__DEVELOPERS', cd)\n",
    "stg_features = snowflake_query('STAGING', 'STG__FEATURES', cd)\n",
    "stg_places = snowflake_query('STAGING', 'STG__PLACES', cd)\n",
    "stg_projects = snowflake_query('STAGING', 'STG__PROJECTS_LIST', cd)\n",
    "stg_transit = snowflake_query('STAGING', 'STG__TRANSIT', cd)\n",
    "stg_vacancy = snowflake_query('STAGING', 'STG__VACANCY', cd)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.9.13 ('bootcamp')",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.13"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "5f407b1b582e764af1de92d08149f3039a2cd11cf3017e26c4cc8e85f5896eb3"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
